routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BuyerController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => 'role:admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::resource('/category', CategoryController::class);
        Route::resource('/user', UserController::class);
    });
    Route::group(['middleware' => 'role:supplier', 'prefix' => 'supplier', 'as' => 'supplier.'], function () {
        Route::get('/dashboard', [SupplierController::class, 'dashboard'])->name('dashboard');
        Route::get('/my-product', [Suppliercontroller::class, 'my_products'])->name('my-products');
        Route::get('/add-product', [ProductController::class, 'index'])->name('add-product');
        Route::post('/add-product/{product}', [SupplierController::class, 'add_product'])->name('add-new-price');
        Route::get('/profile/{user}', [UserController::class, 'show'])->name('profile');
        Route::get('/profile/{user}/edit', [SupplierController::class, 'edit'])->name('profile.edit');
        Route::put('/profile/{user}', [SupplierController::class, 'update'])->name('profile.update');
    });
    Route::group(['middleware' => 'role:buyer', 'prefix' => 'buyer', 'as' => 'buyer.'], function () {
        Route::get('/dashboard', [BuyerController::class, 'dashboard'])->name('dashboard');
    });
    Route::group(['middleware' => 'role:admin|supplier'], function () {
        Route::resource('/product', ProductController::class);
    });

});
//Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
//Route::get('home', [HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function supplier()
    {
        return $this->belongsTo(User::class, 'supplier_id', 'id');
    }

    public function getMarkupPrice()
    {
        return $this->price * ($this->supplier->markup + 100) / 100;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'role_id',
        'markup',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function role ()
    {
        return $this->belongsTo(Role::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Product;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $products = Product::paginate(10);
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductRequest $request
     * @return RedirectResponse
     */
    public function store(ProductRequest $request)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $data = $request->validated();
        $data['slug'] = Str::slug($data['name']);
        $data['image'] = time() . '-' . $data['slug'] . '.' . $request->image->extension();
        $request->image->move(public_path('images/products'), $data['image']);
        Product::create($data);
        return redirect()->route('product.index')->with('status', 'Product has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param $product_slug
     * @return Application|Factory|View
     */
    public function show($product_slug)
    {
        $product = Product::where('slug', $product_slug)->first();
        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $product_slug
     * @return Application|Factory|View
     */
    public function edit($product_slug)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $product = Product::where('slug', $product_slug)->first();
        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductRequest $request
     * @param Product $product
     * @return RedirectResponse
     */
    public function update(ProductRequest $request, Product $product)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $data = $request->validated();
        $data['slug'] = Str::slug($data['name']);
        if(request()->has('image')){
            $data['image'] = time() . '-' . $data['slug'] . '.' . $request->image->extension();
            $request->image->move(public_path('images/products'), $data['image']);
        }
        $product->update($data);
        return redirect()->route('product.index')->with('status', 'Product has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Product $product
     * @return RedirectResponse
     */
    public function destroy(Product $product)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $product->delete();
        return redirect()->back()->with('status', 'Product has been deleted successfully');
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create New Product') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form role="form" action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Product Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Product Name" class="form-control input-md" name="name" value="{{ old('name') }}">
                                    @error('name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Description</label>
                                <div class="col-md-6 offset-md-3">
                                    <textarea placeholder="Description" class="form-control" name="description">{{ old('description') }}</textarea>
                                    @error('description') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Price</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Regular Price" class="form-control input-md" name="price" value="{{ old('price') }}">
                                    @error('price') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Stock</label>
                                <div class="col-md-6 offset-md-3">
                                    <select class="form-control" name="stock_status">
                                        <option value="instock">InStock</option>
                                        <option value="outofstock">Out of Stock</option>
                                    </select>
                                    @error('stock_status') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Quantity</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Quantity" class="form-control input-md" name="quantity" value="{{ old('quantity') }}">
                                    @error('quantity') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Product Image</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="file" class="input-file" name="image">
{{--                                    @if(isset($image))--}}
{{--                                        <img src="{{ $image->temporaryUrl() }}" width="120">--}}
{{--                                    @endif--}}
                                    @error('image') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Category</label>
                                <div class="col-md-6 offset-md-3">
                                    <select class="form-control" name="category_id">
                                        <option value="" selected disabled>Select Category</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->title }}</option>
                                        @endforeach
                                    </select>
                                    @error('category_id') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Supplier</label>
                                <div class="col-md-6 offset-md-3">
                                    <select class="form-control" name="supplier_id">
                                        <option value="" selected disabled>Select Supplier</option>
                                        @foreach($suppliers as $supplier)
                                            <option value="{{ $supplier->id }}">{{ $supplier->full_name }}</option>
                                        @endforeach
                                    </select>
                                    @error('supplier_id') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3"></label>
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('product.index') }}" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit Product') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form role="form" action="{{ route('product.update', $product) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Product Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Product Name" class="form-control input-md" name="name" value="{{ $product->name }}">
                                    @error('name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Description</label>
                                <div class="col-md-6 offset-md-3">
                                    <textarea placeholder="Description" class="form-control" name="description">{{ $product->description }}</textarea>
                                    @error('description') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Price</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Regular Price" class="form-control input-md" name="price" value="{{ $product->price }}">
                                    @error('price') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Stock</label>
                                <div class="col-md-6 offset-md-3">
                                    <select class="form-control" name="stock_status">
                                        <option value="instock" @if($product->stock_status == 'instock') selected @endif>InStock</option>
                                        <option value="outofstock" @if($product->stock_status == 'outofstock') selected @endif>Out of Stock</option>
                                    </select>
                                    @error('stock_status') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Quantity</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Quantity" class="form-control input-md" name="quantity" value="{{ $product->quantity }}">
                                    @error('quantity') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Product Image</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="file" class="input-file" name="image" value="{{ $product->image }}">
                                    {{--                                    @if(isset($image))--}}
                                    {{--                                        <img src="{{ $image->temporaryUrl() }}" width="120">--}}
                                    {{--                                    @endif--}}
                                    @error('image') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Category</label>
                                <div class="col-md-6 offset-md-3">
                                    <select class="form-control" name="category_id">
                                        <option value="" selected disabled>Select Category</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}" @if($product->category_id == $category->id) selected @endif>{{ $category->title }}</option>
                                        @endforeach
                                    </select>
                                    @error('category_id') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3">Supplier</label>
                                <div class="col-md-6 offset-md-3">
                                    <select class="form-control" name="supplier_id">
                                        <option value="" selected disabled>Select Supplier</option>
                                        @foreach($suppliers as $supplier)
                                            <option value="{{ $supplier->id }}" @if($product->supplier_id == $supplier->id) selected @endif>{{ $supplier->full_name }}</option>
                                        @endforeach
                                    </select>
                                    @error('supplier_id') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label offset-md-3"></label>
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                    <a href="{{ route('product.index') }}" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        nav svg {
            height: 20px;
        }
        nav .hidden {
            display: block !important;
        }
        p.text-sm {
            margin-top: 10px;
        }
    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Products table') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @can('admin-only', Auth::user())
                            <a href="{{ route('product.create') }}" class="btn btn-success mb-3">Create New Product</a>
                        @endcan
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Category</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr>

                                    <td>{{ $product->id }}</td>
                                    <td>
                                        <a href="{{ route('product.show', $product->slug) }}">
                                            <img src="{{ asset('images/products')}}/{{ $product->image }}" alt="{{ $product->name }}" width="60">
                                        </a>
                                    </td>
                                    <td><a href="{{ route('product.show', $product->slug) }}" style="text-decoration: none;color: #000">{{ $product->name }}</a></td>
                                    <td>{{ $product->price }}</td>
                                    <td>{{ $product->category->title }}</td>
                                    <td>
                                        <a class="btn btn-success btn-sm" href="{{ route('product.edit', $product->slug) }}" style="padding: 5px 4px !important;"><i
                                                class="fa fa-pencil-square-o"></i></a>

                                        <form action="{{ route('product.destroy', $product) }}" method="post"
                                              id="deleteForm-{{ $product->id }}" style="display: none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <a class="btn btn-danger btn-sm" href="" onclick="
                                            if(confirm('Are you sure you really want to delete this product?')){
                                            event.preventDefault();
                                            document.getElementById('deleteForm-{{ $product->id }}').submit();
                                            }else{
                                            event.preventDefault();
                                            }" style="padding: 5px 5px"><i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                            <div class="justify-content-center">{{ $products->links() }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="row justify-content-between">
                            <h3 class="ml-5">{{ __($product->name) }}</h3>

                            <a href="{{ route('product.index') }}" class="btn btn-outline-dark mr-5">Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <div class="wrap-product-detail">
                            <div class="detail-media">
                                <div class="product-gallery">
                                    <ul class="slides">
                                        <li data-thumb="{{ asset('images/products') }}/{{ $product->image }}">
                                            <img src="{{ asset('images/products') }}/{{ $product->image }}" alt="{{ $product->name }}" />
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="detail-info">
                                <div class="row justify-content-around">
                                    <div class="product-rating">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <a href="#" class="count-review">(05 review)</a>
                                    </div>
                                    <div class="stock-info in-stock">
                                        <p class="availability">Availability:
                                            <span class="{{ $product->stock_status == 'instock' ? 'text-success' : 'text-danger' }}"><b>{{ $product->stock_status }}</b></span>
                                        </p>
                                    </div>
                                </div>
                                <div class="row justify-content-around">
                                    <h2 class="product-name">{{ $product->name }}</h2>
                                    <div class="float-right">
                                        <h1 class="text-primary font-weight-bold" >${{ $product->price }}</h1>
                                    </div>
                                </div>
                                <div class="mx-3">
                                    {{ $product->description }}
                                </div>
                                @can('supplier-only', Auth::user())
                                    <div class="wrap-butons my-5">
                                        <a href="{{ route('supplier.add-new-price', $product) }}" class="btn btn-outline-dark">Add New Price</a>
                                    </div>
                                @endcan
                                @can('user', Auth::user())
                                    <div class="wrap-butons my-5">
                                        <a href="#" class="btn btn-outline-dark">Add to Wishlist</a>
                                    </div>
                                @endcan
                            </div>
                                <table class="shop_attributes">
                                    <tbody>
                                    <tr>
                                        <th>@if($product->category_id != 1) Screen @endif Size</th><td class="product_dimensions">12 x 15 x 23 cm</td>
                                    </tr>
                                    <tr>
                                        <th>Color</th><td>Black, Blue, Grey, Violet, Yellow</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection