routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BuyerController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => 'role:admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::resource('/category', CategoryController::class);
        Route::resource('/user', UserController::class);
    });
    Route::group(['middleware' => 'role:supplier', 'prefix' => 'supplier', 'as' => 'supplier.'], function () {
        Route::get('/dashboard', [SupplierController::class, 'dashboard'])->name('dashboard');
        Route::get('/my-product', [Suppliercontroller::class, 'my_products'])->name('my-products');
        Route::get('/add-product', [ProductController::class, 'index'])->name('add-product');
        Route::post('/add-product/{product}', [SupplierController::class, 'add_product'])->name('add-new-price');
        Route::get('/profile/{user}', [UserController::class, 'show'])->name('profile');
        Route::get('/profile/{user}/edit', [SupplierController::class, 'edit'])->name('profile.edit');
        Route::put('/profile/{user}', [SupplierController::class, 'update'])->name('profile.update');
    });
    Route::group(['middleware' => 'role:buyer', 'prefix' => 'buyer', 'as' => 'buyer.'], function () {
        Route::get('/dashboard', [BuyerController::class, 'dashboard'])->name('dashboard');
    });
    Route::group(['middleware' => 'role:admin|supplier'], function () {
        Route::resource('/product', ProductController::class);
    });

});
//Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
//Route::get('home', [HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'slug'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $categories = Category::all();
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryRequest $request
     * @return RedirectResponse
     */
    public function store(CategoryRequest $request)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $data = $request->validated();
        $data['slug'] = Str::slug($data['title']);
        Category::create($data);
        return redirect()->route('admin.category.index')->with('status', 'Category has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $category_slug
     * @return Application|Factory|View
     */
    public function edit($category_slug)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $category = Category::where('slug', $category_slug)->first();
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryRequest $request
     * @param $category_slug
     * @return RedirectResponse
     */
    public function update(CategoryRequest $request, $category_slug)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $category = Category::where('slug', $category_slug)->first();
        $data = $request->validated();
        $data['slug'] = Str::slug($data['title']);
        $category->update($data);
        return redirect()->route('admin.category.index')->with('status', 'Category has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return RedirectResponse
     */
    public function destroy(Category $category)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $category->delete();
        return redirect()->back()->with('status', 'Category has been deleted successfully');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create New Category') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form role="form" action="{{ route('admin.category.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Category Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter category name" class="form-control input-md" name="title" value="{{ old('title') }}">
                                    @error('title') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3"></label>
                                <div class="col-md-4 offset-md-3">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Update Category') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form role="form" action="{{ route('admin.category.update', $category->slug) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Category Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter category name" class="form-control input-md" name="title" value="{{ $category->title }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3"></label>
                                <div class="col-md-4 offset-md-3">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Categories Table') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <a href="{{ route('admin.category.create') }}" class="btn btn-success mb-3">Create New Category</a>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Category Name</th>
                                <th>Slug</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->title }}</td>
                                    <td>{{ $category->slug }}</td>
                                    <td>
                                        <a class="btn btn-success btn-sm" href="{{ route('admin.category.edit', $category->slug) }}"><i
                                                class="fa fa-pencil-square-o"></i></a>

                                        <form action="{{ route('admin.category.destroy', $category) }}" method="post"
                                              id="deleteForm-{{ $category->id }}" style="display: none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <a class="btn btn-danger btn-sm" href="" onclick="
                                            if(confirm('Are you sure you really want to delete this category?')){
                                            event.preventDefault();
                                            document.getElementById('deleteForm-{{ $category->id }}').submit();
                                            }else{
                                            event.preventDefault();
                                            }"><i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection