routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BuyerController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => 'role:admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::resource('/category', CategoryController::class);
        Route::resource('/user', UserController::class);
    });
    Route::group(['middleware' => 'role:supplier', 'prefix' => 'supplier', 'as' => 'supplier.'], function () {
        Route::get('/dashboard', [SupplierController::class, 'dashboard'])->name('dashboard');
        Route::get('/my-product', [Suppliercontroller::class, 'my_products'])->name('my-products');
        Route::get('/add-product', [ProductController::class, 'index'])->name('add-product');
        Route::post('/add-product/{product}', [SupplierController::class, 'add_product'])->name('add-new-price');
        Route::get('/profile/{user}', [UserController::class, 'show'])->name('profile');
        Route::get('/profile/{user}/edit', [SupplierController::class, 'edit'])->name('profile.edit');
        Route::put('/profile/{user}', [SupplierController::class, 'update'])->name('profile.update');
    });
    Route::group(['middleware' => 'role:buyer', 'prefix' => 'buyer', 'as' => 'buyer.'], function () {
        Route::get('/dashboard', [BuyerController::class, 'dashboard'])->name('dashboard');
    });
    Route::group(['middleware' => 'role:admin|supplier'], function () {
        Route::resource('/product', ProductController::class);
    });

});
//Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
//Route::get('home', [HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'role_id',
        'markup',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function role ()
    {
        return $this->belongsTo(Role::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{

    public function index()
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $users = User::all();
        return view('user.index', compact('users'));
    }

    public function create()
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        return view('user.create');
    }

    public function store(UserRequest $request)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $data = $request->validated();
        $data['password'] = bcrypt('123456789');
        User::create($data);
        return redirect()->route('admin.user.index')->with('status', 'User has been created successfully');
    }

    public function show(User $user)
    {
        if(! Gate::allows('supplier-only')) {
            return abort(401);
        }
        return view('user.show', compact('user'));
    }

    public function edit(User $user)
    {
//        if(! Gate::allows('admin-only')) {
//            return abort(401);
//        }
        return view('user.edit', compact('user'));
    }

    public function update(UserUpdateRequest $request, User $user )
    {
        return $request;
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $data = $request->validated();
        $user->update($data);
        return redirect()->route('admin.user.index')->with('status', 'User has been updated successfully');
    }

    public function destroy (User $user)
    {
        if(! Gate::allows('admin-only')) {
            return abort(401);
        }
        $user->delete();
        return redirect()->back()->with('status', 'User has been deleted successfully');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create New User') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form role="form" action="{{ route('admin.user.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">First Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter user first name" class="form-control input-md" name="first_name" value="{{ old('first_name') }}">
                                    @error('first_name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Last Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter user last name" class="form-control input-md" name="last_name" value="{{ old('last_name') }}">
                                    @error('last_name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">User Email</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="email" placeholder="Enter user email" class="form-control input-md" name="email" value="{{ old('email') }}">
                                    @error('email') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">User Role</label>
                                <div class="col-md-6 offset-md-3">
                                    <select name="role_id" id="role_id" class="form-control">
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}" @if($role->id == 3) selected @endif>{{ $role->role }}</option>
                                        @endforeach
                                    </select>
                                    @error('role_id') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Markup</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="number" placeholder="Enter a percentage markup" class="form-control" name="markup" value="{{ old('markup') }}">
                                    @error('markup') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3"></label>
                                <div class="col-md-4 offset-md-3">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('admin.user.index') }}" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/edit-supplier.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit User Data') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form role="form" action="{{ route('supplier.profile.update', $user) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">First Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter user first name" class="form-control input-md" name="first_name" value="{{ $user->first_name }}">
                                    @error('first_name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Last Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter user last name" class="form-control input-md" name="last_name" value="{{ $user->last_name }}">
                                    @error('last_name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">User Email</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="email" placeholder="Enter user email" class="form-control input-md" name="email" value="{{ $user->email }}">
                                    @error('email') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Change Password</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter new password" class="form-control" name="password" autocomplete="off" value="{{ old('password') }}">
                                    @error('password') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3"></label>
                                <div class="col-md-4 offset-md-3">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                    <a href="{{ route('supplier.profile', $user) }}" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit User Data') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form role="form" action="{{ route('admin.user.update', $user) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">First Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter user first name" class="form-control input-md" name="first_name" value="{{ $user->first_name }}">
                                    @error('first_name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Last Name</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="text" placeholder="Enter user last name" class="form-control input-md" name="last_name" value="{{ $user->last_name }}">
                                    @error('last_name') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">User Email</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="email" placeholder="Enter user email" class="form-control input-md" name="email" value="{{ $user->email }}">
                                    @error('email') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">User Role</label>
                                <div class="col-md-6 offset-md-3">
                                    <select name="role_id" id="role_id" class="form-control">
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}" @if($role->id == $user->role_id) selected @endif>{{ $role->role }}</option>
                                        @endforeach
                                    </select>
                                    @error('role_id') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3">Markup</label>
                                <div class="col-md-6 offset-md-3">
                                    <input type="number" placeholder="Enter a percentage markup" class="form-control" name="markup" value="{{ $user->markup }}">
                                    @error('markup') <span class="text-danger error"><small>{{ $message }}</small></span>@enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-md-4 control-label offset-md-3"></label>
                                <div class="col-md-4 offset-md-3">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                    <a href="{{ route('admin.user.index') }}" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Users Table') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <a href="{{ route('admin.user.create') }}" class="btn btn-success mb-3">Create New User</a>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Markup</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->full_name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->role->role }}</td>
                                    <td>{{ isset($user->markup) ? $user->markup . '%' : ''}}</td>
                                    <td>
                                        <a class="btn btn-success btn-sm" href="{{ route('admin.user.edit', $user->id) }}"><i
                                                class="fa fa-pencil-square-o"></i></a>

                                        <form action="{{ route('admin.user.destroy', $user) }}" method="post"
                                              id="deleteForm-{{ $user->id }}" style="display: none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <a class="btn btn-danger btn-sm" href="" onclick="
                                            if(confirm('Are you sure you really want to delete this user?')){
                                            event.preventDefault();
                                            document.getElementById('deleteForm-{{ $user->id }}').submit();
                                            }else{
                                            event.preventDefault();
                                            }"><i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Profile') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->full_name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->role->role }}</td>
                                    <td>
                                        <a class="btn btn-success btn-sm" href="{{ route('supplier.profile.edit', $user) }}"><i
                                                class="fa fa-pencil-square-o"></i></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection